version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    container_name: python-app

  db:
    image: postgres:latest
    restart: always
    env_file:
      - .db.env
    ports:
      - "5432:5432"
    
    container_name: postgres-db

